[package]
name = "regexp2"
version = "0.1.0"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
automata = { path = "../automata" }
tree = { git = "https://github.com/apasel422/tree.git" }
