[package]
name = "regexp2"
version = "0.1.0"
authors = ["Eric Zhao <21zhaoe@protonmail.com>"]
edition = "2018"
license = "MIT"

[package.metadata]
msrv = "1.46.0"

[dependencies]
automata = { path = "../automata" }

im = "15.0"
thiserror = "1.0"
